#include "../include/SecurityConfig.h"
#include <fstream>
#include <sstream>
#include <cctype>

bool SecurityConfig::loadFromFile(const std::string& filename) {
    std::ifstream file(filename);
    if (!file.is_open()) {
        return false;
    }

    std::string line;
    while (std::getline(file, line)) {
        // Skip comments and empty lines
        if (line.empty() || line[0] == '#') {
            continue;
        }

        size_t pos = line.find('=');
        if (pos == std::string::npos) {
            continue;
        }

        std::string key = line.substr(0, pos);
        std::string value = line.substr(pos + 1);

        // Trim whitespace
        key.erase(0, key.find_first_not_of(" \t"));
        key.erase(key.find_last_not_of(" \t") + 1);
        value.erase(0, value.find_first_not_of(" \t"));
        value.erase(value.find_last_not_of(" \t") + 1);

        // Parse configuration values
        if (key == "minPasswordLength") minPasswordLength = std::stoi(value);
        else if (key == "maxPasswordLength") maxPasswordLength = std::stoi(value);
        else if (key == "requireUppercase") requireUppercase = (value == "true" || value == "1");
        else if (key == "requireLowercase") requireLowercase = (value == "true" || value == "1");
        else if (key == "requireDigits") requireDigits = (value == "true" || value == "1");
        else if (key == "requireSpecialChars") requireSpecialChars = (value == "true" || value == "1");
        else if (key == "enable2FA") enable2FA = (value == "true" || value == "1");
        else if (key == "totpTimeStep") totpTimeStep = std::stoi(value);
        else if (key == "totpDigits") totpDigits = std::stoi(value);
        else if (key == "enableEncryption") enableEncryption = (value == "true" || value == "1");
        else if (key == "encryptionAlgorithm") encryptionAlgorithm = value;
        else if (key == "sessionTimeoutMinutes") sessionTimeoutMinutes = std::stoi(value);
        else if (key == "maxFailedAttempts") maxFailedAttempts = std::stoi(value);
        else if (key == "lockoutDurationMinutes") lockoutDurationMinutes = std::stoi(value);
        else if (key == "saltLength") saltLength = std::stoi(value);
        else if (key == "hashIterations") hashIterations = std::stoi(value);
        else if (key == "enableAccountLockout") enableAccountLockout = (value == "true" || value == "1");
        else if (key == "enableSessionTracking") enableSessionTracking = (value == "true" || value == "1");
        else if (key == "logFailedAttempts") logFailedAttempts = (value == "true" || value == "1");
    }

    file.close();
    return true;
}

bool SecurityConfig::saveToFile(const std::string& filename) const {
    std::ofstream file(filename);
    if (!file.is_open()) {
        return false;
    }

    file << "# Security Configuration File\n";
    file << "# Generated by SecureAuthSystem\n\n";

    file << "# Password Policy\n";
    file << "minPasswordLength=" << minPasswordLength << "\n";
    file << "maxPasswordLength=" << maxPasswordLength << "\n";
    file << "requireUppercase=" << (requireUppercase ? "true" : "false") << "\n";
    file << "requireLowercase=" << (requireLowercase ? "true" : "false") << "\n";
    file << "requireDigits=" << (requireDigits ? "true" : "false") << "\n";
    file << "requireSpecialChars=" << (requireSpecialChars ? "true" : "false") << "\n\n";

    file << "# Two-Factor Authentication\n";
    file << "enable2FA=" << (enable2FA ? "true" : "false") << "\n";
    file << "totpTimeStep=" << totpTimeStep << "\n";
    file << "totpDigits=" << totpDigits << "\n\n";

    file << "# Encryption\n";
    file << "enableEncryption=" << (enableEncryption ? "true" : "false") << "\n";
    file << "encryptionAlgorithm=" << encryptionAlgorithm << "\n\n";

    file << "# Session Management\n";
    file << "sessionTimeoutMinutes=" << sessionTimeoutMinutes << "\n";
    file << "maxFailedAttempts=" << maxFailedAttempts << "\n";
    file << "lockoutDurationMinutes=" << lockoutDurationMinutes << "\n\n";

    file << "# Password Hashing\n";
    file << "saltLength=" << saltLength << "\n";
    file << "hashIterations=" << hashIterations << "\n\n";

    file << "# Account Security\n";
    file << "enableAccountLockout=" << (enableAccountLockout ? "true" : "false") << "\n";
    file << "enableSessionTracking=" << (enableSessionTracking ? "true" : "false") << "\n";
    file << "logFailedAttempts=" << (logFailedAttempts ? "true" : "false") << "\n";

    file.close();
    return true;
}

bool SecurityConfig::validatePassword(const std::string& password) const {
    if (password.length() < minPasswordLength || password.length() > maxPasswordLength) {
        return false;
    }

    bool hasUpper = false, hasLower = false, hasDigit = false, hasSpecial = false;

    for (char c : password) {
        if (std::isupper(c)) hasUpper = true;
        else if (std::islower(c)) hasLower = true;
        else if (std::isdigit(c)) hasDigit = true;
        else if (std::ispunct(c) || std::isspace(c)) hasSpecial = true;
    }

    if (requireUppercase && !hasUpper) return false;
    if (requireLowercase && !hasLower) return false;
    if (requireDigits && !hasDigit) return false;
    if (requireSpecialChars && !hasSpecial) return false;

    return true;
}

std::string SecurityConfig::toString() const {
    std::stringstream ss;
    ss << "Security Configuration:\n";
    ss << "  Password Length: " << minPasswordLength << "-" << maxPasswordLength << "\n";
    ss << "  Require: ";
    if (requireUppercase) ss << "Uppercase ";
    if (requireLowercase) ss << "Lowercase ";
    if (requireDigits) ss << "Digits ";
    if (requireSpecialChars) ss << "Special ";
    ss << "\n";
    ss << "  2FA Enabled: " << (enable2FA ? "Yes" : "No") << "\n";
    ss << "  Encryption: " << (enableEncryption ? encryptionAlgorithm : "Disabled") << "\n";
    ss << "  Session Timeout: " << sessionTimeoutMinutes << " minutes\n";
    ss << "  Max Failed Attempts: " << maxFailedAttempts << "\n";
    ss << "  Account Lockout: " << (enableAccountLockout ? "Enabled" : "Disabled") << "\n";
    return ss.str();
}
